# snippets_panos is used to load a basic GlobalProtect configuration
# snippet folder name

name: Basic_GP_Configuration_dhcp_v90

# label used for menu selection
label: v9.0 GlobalProtect Basic with DHCP Untrust Intf
description: GlobalProtect basic configuration with DHCP untrust interface and local user DB
dependency:

# type of device configuration
type: panos
# panos or panorama or panorama_gpcs

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: globalprotect
  collection: globalprotect

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc

variables:

# Cert and auth profile values
  - name: ssl_tls_service_profile
    description: Gateway-1 and Portal-1 - SSL TLS Service Profile
    default: ssl_tls_service_profile
    type_hint: text
  - name: trusted_CA
    description: Portal-1 - Trusted certificate of authority
    default: GP_Root_CA
    type_hint: text
  - name: Server_certificate
    description: SSL Server Certificate name
    default: GP_Server
    type_hint: text

# Portal values
  - name: portal_name
    description: Portal-1 - Reference name for the GP portal
    default: Portal-1
    type_hint: text
  - name: portal_intf
    description: Portal-1 - Interface mapped to the GP portal
    default: ethernet1/1
    type_hint: text

# Gateway values
  - name: gateway_name
    description: Gateway-1 - Reference name for the GP gateway
    default: Gateway-1
    type_hint: text
  - name: gateway_intf
    description: Interface mapped to the GP gateway (ethernet1/n)
    default: ethernet1/1
    type_hint: text
  - name: gateway_fqdn
    description: FQDN used for gateway access (must match server cert FQDN)
    default: gp.fqdn.com
    type_hint: text
  - name: user_ip_pool
    description: Gateway-1 - IP pool assigned to GP users
    default: 10.10.10.2-10.10.10.100
    type_hint: text

# tunnel parameters
  - name: tunnel_name
    description: Tunnel Interface - tunnel interface name
    default: tunnel.100
    type_hint: text
  - name: tunnel_ip_address
    description: Tunnel Interface -  Interface IP address
    default: 10.10.10.1
    type_hint: ip_address
  - name: gp_vr
    description: Virtual Router used for GP tunnel interface
    default: default
    type_hint: text
  - name: tunnel_zone
    description: Zone used for the GlobalProtect tunnel interface
    default: GP_zone
    type_hint: text
  - name: Trusted_zone
    description: Name of the trusted zone to allow tunnel zone access
    default: Trust
    type_hint: text
  - name: Untrusted_zone
    description: Name of the untrusted zone to allow tunnel zone access
    default: Untrust
    type_hint: text

snippets:
# SSL/TLS Service Profile
    - name: ssl_tls_profile
      xpath: /config/shared/ssl-tls-service-profile
      file: 0-ssl_tls_profile.xml
# Tunnel Interface
    - name: tunnel_interface
      xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface  
      file: 1-Tunnel_Interface.xml
# Virtual Router
    - name: virtual_router_upate
      xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
      file: 2-Modify_Virtual_Router.xml
# Tunnel Interface zone
    - name: tunnel_interface_zone
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
      file: 3-Tunnel_Interface_zone.xml
# Local Test User Database
    - name: Test user database
      xpath: /config/shared/local-user-database
      file: 4-Local_Test_User_Database.xml
# Local Test User Authentication Profile
    - name: Test user database
      xpath: /config/shared/authentication-profile
      file: 5-Local_Test_User_Authentication_Profile.xml
# Gateway-1-N
    - name: gateway-1-N_configuration
      xpath: /config/devices/entry[@name='localhost.localdomain']/network/tunnel/global-protect-gateway
      file: 7-Gateway-1-N.xml
# Gateway-1  
    - name: gateway-1_configuration
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-gateway
      file: 6-Gateway-1.xml
# Portal-1  
    - name: portal-1_configuration
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-portal
      file: 8-Portal-1.xml
# Rulebase
    - name: Rulebase
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
      file: 9-Rulebase.xml
# Source NAT for the tunnel zone
  - name: nat-source-nat-to-untrust
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat
    file: source_nat_to_untrust.xml